### ISSUE TITLE
Fiture Recrest Lan Chat

### ISSUE THREAD

**Issue by Scratchinator** [PascalCorpsman/mini_projects#2]
Kan man es sicht bar machen wei bei signal das wen der andere gerade schreibt das dan dort wo dan die naricht erscheinen würde solche bunkte in einer reihe immer dicker und dünner werden oder etwas anderes?

**Comment by PascalCorpsman** [comment]
Dieses Feature ist Datenschutztechnisch sehr "bedenklich", daher wird das nicht umgesetzt
