### ISSUE TITLE
Have you considered joining the [LXQT](https://lxqt-project.org/about/) project?

### ISSUE THREAD

**Issue by theavege** [PascalCorpsman/mini_projects#4]
Have you considered joining the [LXQT](https://lxqt-project.org/about/) project?
I think that joining Lazarus programs to the LXQT project will be mutually beneficial.

**Comment by PascalCorpsman** [comment]
thanks for the offer, i publish my programs with all it's source, so if any project or potential user want to use them its already possible. Including them into a "Project" would unnecessarily restrict this, so i don't see a point here.
Sorry.
