### ISSUE TITLE
uunbufstringlist

### ISSUE THREAD

**Issue by theavege** [PascalCorpsman/mini_projects#5]
Where can I found "uunbufstringlist"?

**Comment by PascalCorpsman** [comment]
i don't get it, i don't know this component, neither use it.

**Comment by theavege** [comment]
@PascalCorpsman 

`miniprojects/3d_Printer/Extruder_Calibrator/u3d_printer.pas:52:  Classes, SysUtils, synaser, pitools, upilogger, uunbufstringlist;`
